### ISSUE TITLE
Connected then disconnected immediatly

### ISSUE THREAD

**Issue by ThibaultNocchi** [hkchai/SecretSocks#1]
I have a problem when connecting to the server with your app.
I put my server IP, my server port (443), my username and my password, and the SOCKS port (8181).
Then, I click on Connect and here the status : 

Connecting...
Success!
Not Connected.

And that's all.
I don't know why it bugs, but when I made ssh -D 8181 -p 443 user@ip, it works well!

Thank you in advance.

**Comment by hkchai** [comment]
This issue is due to version mismatch of underlying SSL shared library after Apple's update. Now I statically linked the library to the app. Should resolve it now.
